#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto:  
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: false
#        default_batch_fetch_size: 100 # ?? ????? ???

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.hibernate.orm.jdbc.bind: trace


# jwt 시크릿 코드 변수
#  jwt:
#    secret: askdlaskdlasaskdlask
# 여기에서 secret은 변수명임
# JWT Util에서 사용할 변수명
